# Generated by Django 4.2.23 on 2025-08-03 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_studentmodel_create_at_studentmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
