# Generated by Django 4.2.23 on 2025-08-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_studentmodel_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
